name=PropertiesConfig
property.filename = logs
appenders = console, file

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

appender.file.type = File
appender.file.name = LOGFILE
appender.file.fileName=${filename}/Mylogs.log
appender.file.layout.type=PatternLayout
appender.file.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n
appender.file.append = false

#file logger : Specific Logger Configuration for a Particular Class
loggers=file
logger.file.name=test.PracticeTests.LoggingTest
logger.file.level = info
logger.file.appenderRefs = file
logger.file.appenderRef.file.ref = LOGFILE
# Add additivity = false to avoid child loggers inheriting appenders from parent loggers
logger.file.additivity  = false

#root logger for console
rootLogger.level = debug
rootLogger.appenderRefs = console
rootLogger.appenderRef.stdout.ref = STDOUT

#root logger for file
rootLogger.level = debug
rootLogger.appenderRefs = file
rootLogger.appenderRef.file.ref = LOGFILE